// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqDhpjwimO_68ltoKh7u8uaXMAgPzAWs',
    appId: '1:854889946914:web:4817abc122d54375078f7b',
    messagingSenderId: '854889946914',
    projectId: 'blocpocfirebase',
    authDomain: 'blocpocfirebase.firebaseapp.com',
    storageBucket: 'blocpocfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_029x5DjDoWRkFOfZWbWYqHNscFgdNQ',
    appId: '1:854889946914:android:a25a8366f80e8d3f078f7b',
    messagingSenderId: '854889946914',
    projectId: 'blocpocfirebase',
    storageBucket: 'blocpocfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_lLdSoA6n6rCkKthgRvh7rw74vllDoBU',
    appId: '1:854889946914:ios:245115ca8be8b0c2078f7b',
    messagingSenderId: '854889946914',
    projectId: 'blocpocfirebase',
    storageBucket: 'blocpocfirebase.appspot.com',
    iosClientId: '854889946914-vcghih0tfbfb3alkeik8icvr4h72nnuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocMvvmPocApp',
  );
}
